// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RenderLifeBar","status":true,"description":"Pasek Życia jako pasek postępu renderowania wideo. Gdy dojdzie do końca - Game Over.","parameters":{"barWidth":"300","barHeight":"20","barX":"10","barY":"10","fillSpeed":"0.3","normalColor":"#00cc66","warningColor":"#ffaa00","errorColor":"#ff2222","labelNormal":"Renderowanie...","labelError":"Error","showPercent":"true","gameOverDelay":"90"}}
];
