// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RenderLifeBar","status":true,"description":"Pasek Życia jako pasek postępu renderowania wideo. Gdy dojdzie do końca - Game Over.","parameters":{"barWidth":"300","barHeight":"20","barX":"10","barY":"10","fillSpeed":"0.3","normalColor":"#00cc66","warningColor":"#ffaa00","errorColor":"#ff2222","labelNormal":"Renderowanie...","labelError":"Error","showPercent":"true","gameOverDelay":"90"}},
{"name":"FilmEditingMenu","status":true,"description":"Menu Główne stylizowane na stół montażowy z taśmą filmową.","parameters":{"gameTitle":"13 Klatka - Polowanie na Pozera","subtitle":"editing suite · main timeline","newGameText":"Nowa Gra","continueText":"Wczytaj","optionsText":"Opcje","exitText":"Wyjście","newGameDesc":"rozpocznij nagranie","continueDesc":"kontynuuj nagranie","optionsDesc":"ustawienia montażu","exitDesc":"koniec sesji","colorAmber":"#c8912a","colorBg":"#1a1510","colorDark":"#0d0b08","colorCream":"#e8dfc0"}},
{"name":"FilmSaveLoad","status":true,"description":"Ekran Wczytaj/Zapisz stylizowany na stół montażowy. Wymaga FilmEditingMenu.js","parameters":{"maxSlots":"8","slotsVisible":"5","colorAmber":"#c8912a","colorBg":"#1a1510","colorDark":"#0d0b08","colorCream":"#e8dfc0","emptySlotText":"pusty slot","confirmOverwrite":"true"}}
];
